const express = require('express');
const req = require('express/lib/request');
const { send } = require('express/lib/response');
const res = require('express/lib/response');
const { func } = require('joi');
const app = express();
const Joi = require('joi');

app.use(express.json());

const port = process.env.PORT || 3000;

const listChoices = [
  {
    id: 1,
    species: "Monumen Nasional",
    island: "Torgersen",
    bill_length_mm: 39.1,
    bill_depth_mm: 18.7,
    flipper_length_mm: 181,
    body_mass_g: "3.750,00",
    sex: "male",
    year: 2007
  },
  {
    id: 2,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 39.5,
    bill_depth_mm: 17.4,
    flipper_length_mm: 186,
    body_mass_g: "3.800,00",
    sex: "female",
    year: 2007
  },
  {
    id: 3,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 40.3,
    bill_depth_mm: 18,
    flipper_length_mm: 195,
    body_mass_g: "3.250,00",
    sex: "female",
    year: 2007
  },
  {
    id: 4,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: "NA",
    bill_depth_mm: "NA",
    flipper_length_mm: "NA",
    body_mass_g: "NA",
    sex: "NA",
    year: 2007
  },
  {
    id: 5,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 36.7,
    bill_depth_mm: 19.3,
    flipper_length_mm: 193,
    body_mass_g: "3.450,00",
    sex: "female",
    year: 2007
  },
  {
    id: 6,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 39.3,
    bill_depth_mm: 20.6,
    flipper_length_mm: 190,
    body_mass_g: "3.650,00",
    sex: "male",
    year: 2007
  },
  {
    id: 7,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 38.9,
    bill_depth_mm: 17.8,
    flipper_length_mm: 181,
    body_mass_g: "3.625,00",
    sex: "female",
    year: 2007
  },
  {
    id: 8,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 39.2,
    bill_depth_mm: 19.6,
    flipper_length_mm: 195,
    body_mass_g: "4.675,00",
    sex: "male",
    year: 2007
  },
  {
    id: 9,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 34.1,
    bill_depth_mm: 18.1,
    flipper_length_mm: 193,
    body_mass_g: "3.475,00",
    sex: "NA",
    year: 2007
  },
  {
    id: 10,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 42,
    bill_depth_mm: 20.2,
    flipper_length_mm: 190,
    body_mass_g: "4.250,00",
    sex: "NA",
    year: 2007
  },
  {
    id: 11,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 37.8,
    bill_depth_mm: 17.1,
    flipper_length_mm: 186,
    body_mass_g: "3.300,00",
    sex: "NA",
    year: 2007
  },
  {
    id: 12,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 37.8,
    bill_depth_mm: 17.3,
    flipper_length_mm: 180,
    body_mass_g: "3.700,00",
    sex: "NA",
    year: 2007
  },
  {
    id: 13,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 41.1,
    bill_depth_mm: 17.6,
    flipper_length_mm: 182,
    body_mass_g: "3.200,00",
    sex: "female",
    year: 2007
  },
  {
    id: 14,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 38.6,
    bill_depth_mm: 21.2,
    flipper_length_mm: 191,
    body_mass_g: "3.800,00",
    sex: "male",
    year: 2007
  },
  {
    id: 15,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 34.6,
    bill_depth_mm: 21.1,
    flipper_length_mm: 198,
    body_mass_g: "4.400,00",
    sex: "male",
    year: 2007
  },
  {
    id: 16,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 36.6,
    bill_depth_mm: 17.8,
    flipper_length_mm: 185,
    body_mass_g: "3.700,00",
    sex: "female",
    year: 2007
  },
  {
    id: 17,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 38.7,
    bill_depth_mm: 19,
    flipper_length_mm: 195,
    body_mass_g: "3.450,00",
    sex: "female",
    year: 2007
  },
  {
    id: 18,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 42.5,
    bill_depth_mm: 20.7,
    flipper_length_mm: 197,
    body_mass_g: "4.500,00",
    sex: "male",
    year: 2007
  },
  {
    id: 19,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 34.4,
    bill_depth_mm: 18.4,
    flipper_length_mm: 184,
    body_mass_g: "3.325,00",
    sex: "female",
    year: 2007
  },
  {
    id: 20,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 46,
    bill_depth_mm: 21.5,
    flipper_length_mm: 194,
    body_mass_g: "4.200,00",
    sex: "male",
    year: 2007
  },
  {
    id: 21,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 37.8,
    bill_depth_mm: 18.3,
    flipper_length_mm: 174,
    body_mass_g: "3.400,00",
    sex: "female",
    year: 2007
  },
  {
    id: 22,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 37.7,
    bill_depth_mm: 18.7,
    flipper_length_mm: 180,
    body_mass_g: "3.600,00",
    sex: "male",
    year: 2007
  },
  {
    id: 23,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 35.9,
    bill_depth_mm: 19.2,
    flipper_length_mm: 189,
    body_mass_g: "3.800,00",
    sex: "female",
    year: 2007
  },
  {
    id: 24,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 38.2,
    bill_depth_mm: 18.1,
    flipper_length_mm: 185,
    body_mass_g: "3.950,00",
    sex: "male",
    year: 2007
  },
  {
    id: 25,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 38.8,
    bill_depth_mm: 17.2,
    flipper_length_mm: 180,
    body_mass_g: "3.800,00",
    sex: "male",
    year: 2007
  },
  {
    id: 26,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 35.3,
    bill_depth_mm: 18.9,
    flipper_length_mm: 187,
    body_mass_g: "3.800,00",
    sex: "female",
    year: 2007
  },
  {
    id: 27,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 40.6,
    bill_depth_mm: 18.6,
    flipper_length_mm: 183,
    body_mass_g: "3.550,00",
    sex: "male",
    year: 2007
  },
  {
    id: 28,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 40.5,
    bill_depth_mm: 17.9,
    flipper_length_mm: 187,
    body_mass_g: "3.200,00",
    sex: "female",
    year: 2007
  },
  {
    id: 29,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 37.9,
    bill_depth_mm: 18.6,
    flipper_length_mm: 172,
    body_mass_g: "3.150,00",
    sex: "female",
    year: 2007
  },
  {
    id: 30,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 40.5,
    bill_depth_mm: 18.9,
    flipper_length_mm: 180,
    body_mass_g: "3.950,00",
    sex: "male",
    year: 2007
  },
  {
    id: 31,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 39.5,
    bill_depth_mm: 16.7,
    flipper_length_mm: 178,
    body_mass_g: "3.250,00",
    sex: "female",
    year: 2007
  },
  {
    id: 32,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 37.2,
    bill_depth_mm: 18.1,
    flipper_length_mm: 178,
    body_mass_g: "3.900,00",
    sex: "male",
    year: 2007
  },
  {
    id: 33,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 39.5,
    bill_depth_mm: 17.8,
    flipper_length_mm: 188,
    body_mass_g: "3.300,00",
    sex: "female",
    year: 2007
  },
  {
    id: 34,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 40.9,
    bill_depth_mm: 18.9,
    flipper_length_mm: 184,
    body_mass_g: "3.900,00",
    sex: "male",
    year: 2007
  },
  {
    id: 35,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 36.4,
    bill_depth_mm: 17,
    flipper_length_mm: 195,
    body_mass_g: "3.325,00",
    sex: "female",
    year: 2007
  },
  {
    id: 36,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 39.2,
    bill_depth_mm: 21.1,
    flipper_length_mm: 196,
    body_mass_g: "4.150,00",
    sex: "male",
    year: 2007
  },
  {
    id: 37,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 38.8,
    bill_depth_mm: 20,
    flipper_length_mm: 190,
    body_mass_g: "3.950,00",
    sex: "male",
    year: 2007
  },
  {
    id: 38,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 42.2,
    bill_depth_mm: 18.5,
    flipper_length_mm: 180,
    body_mass_g: "3.550,00",
    sex: "female",
    year: 2007
  },
  {
    id: 39,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 37.6,
    bill_depth_mm: 19.3,
    flipper_length_mm: 181,
    body_mass_g: "3.300,00",
    sex: "female",
    year: 2007
  },
  {
    id: 40,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 39.8,
    bill_depth_mm: 19.1,
    flipper_length_mm: 184,
    body_mass_g: "4.650,00",
    sex: "male",
    year: 2007
  },
  {
    id: 41,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 36.5,
    bill_depth_mm: 18,
    flipper_length_mm: 182,
    body_mass_g: "3.150,00",
    sex: "female",
    year: 2007
  },
  {
    id: 42,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 40.8,
    bill_depth_mm: 18.4,
    flipper_length_mm: 195,
    body_mass_g: "3.900,00",
    sex: "male",
    year: 2007
  },
  {
    id: 43,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 36,
    bill_depth_mm: 18.5,
    flipper_length_mm: 186,
    body_mass_g: "3.100,00",
    sex: "female",
    year: 2007
  },
  {
    id: 44,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 44.1,
    bill_depth_mm: 19.7,
    flipper_length_mm: 196,
    body_mass_g: "4.400,00",
    sex: "male",
    year: 2007
  },
  {
    id: 45,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 37,
    bill_depth_mm: 16.9,
    flipper_length_mm: 185,
    body_mass_g: "3.000,00",
    sex: "female",
    year: 2007
  },
  {
    id: 46,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 39.6,
    bill_depth_mm: 18.8,
    flipper_length_mm: 190,
    body_mass_g: "4.600,00",
    sex: "male",
    year: 2007
  },
  {
    id: 47,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 41.1,
    bill_depth_mm: 19,
    flipper_length_mm: 182,
    body_mass_g: "3.425,00",
    sex: "male",
    year: 2007
  },
  {
    id: 48,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 37.5,
    bill_depth_mm: 18.9,
    flipper_length_mm: 179,
    body_mass_g: "2.975,00",
    sex: "NA",
    year: 2007
  },
  {
    id: 49,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 36,
    bill_depth_mm: 17.9,
    flipper_length_mm: 190,
    body_mass_g: "3.450,00",
    sex: "female",
    year: 2007
  },
  {
    id: 50,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 42.3,
    bill_depth_mm: 21.2,
    flipper_length_mm: 191,
    body_mass_g: "4.150,00",
    sex: "male",
    year: 2007
  },
  {
    id: 51,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 39.6,
    bill_depth_mm: 17.7,
    flipper_length_mm: 186,
    body_mass_g: "3.500,00",
    sex: "female",
    year: 2008
  },
  {
    id: 52,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 40.1,
    bill_depth_mm: 18.9,
    flipper_length_mm: 188,
    body_mass_g: "4.300,00",
    sex: "male",
    year: 2008
  },
  {
    id: 53,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 35,
    bill_depth_mm: 17.9,
    flipper_length_mm: 190,
    body_mass_g: "3.450,00",
    sex: "female",
    year: 2008
  },
  {
    id: 54,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 42,
    bill_depth_mm: 19.5,
    flipper_length_mm: 200,
    body_mass_g: "4.050,00",
    sex: "male",
    year: 2008
  },
  {
    id: 55,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 34.5,
    bill_depth_mm: 18.1,
    flipper_length_mm: 187,
    body_mass_g: "2.900,00",
    sex: "female",
    year: 2008
  },
  {
    id: 56,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 41.4,
    bill_depth_mm: 18.6,
    flipper_length_mm: 191,
    body_mass_g: "3.700,00",
    sex: "male",
    year: 2008
  },
  {
    id: 57,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 39,
    bill_depth_mm: 17.5,
    flipper_length_mm: 186,
    body_mass_g: "3.550,00",
    sex: "female",
    year: 2008
  },
  {
    id: 58,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 40.6,
    bill_depth_mm: 18.8,
    flipper_length_mm: 193,
    body_mass_g: "3.800,00",
    sex: "male",
    year: 2008
  },
  {
    id: 59,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 36.5,
    bill_depth_mm: 16.6,
    flipper_length_mm: 181,
    body_mass_g: "2.850,00",
    sex: "female",
    year: 2008
  },
  {
    id: 60,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 37.6,
    bill_depth_mm: 19.1,
    flipper_length_mm: 194,
    body_mass_g: "3.750,00",
    sex: "male",
    year: 2008
  },
  {
    id: 61,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 35.7,
    bill_depth_mm: 16.9,
    flipper_length_mm: 185,
    body_mass_g: "3.150,00",
    sex: "female",
    year: 2008
  },
  {
    id: 62,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 41.3,
    bill_depth_mm: 21.1,
    flipper_length_mm: 195,
    body_mass_g: "4.400,00",
    sex: "male",
    year: 2008
  },
  {
    id: 63,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 37.6,
    bill_depth_mm: 17,
    flipper_length_mm: 185,
    body_mass_g: "3.600,00",
    sex: "female",
    year: 2008
  },
  {
    id: 64,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 41.1,
    bill_depth_mm: 18.2,
    flipper_length_mm: 192,
    body_mass_g: "4.050,00",
    sex: "male",
    year: 2008
  },
  {
    id: 65,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 36.4,
    bill_depth_mm: 17.1,
    flipper_length_mm: 184,
    body_mass_g: "2.850,00",
    sex: "female",
    year: 2008
  },
  {
    id: 66,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 41.6,
    bill_depth_mm: 18,
    flipper_length_mm: 192,
    body_mass_g: "3.950,00",
    sex: "male",
    year: 2008
  },
  {
    id: 67,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 35.5,
    bill_depth_mm: 16.2,
    flipper_length_mm: 195,
    body_mass_g: "3.350,00",
    sex: "female",
    year: 2008
  },
  {
    id: 68,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 41.1,
    bill_depth_mm: 19.1,
    flipper_length_mm: 188,
    body_mass_g: "4.100,00",
    sex: "male",
    year: 2008
  },
  {
    id: 69,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 35.9,
    bill_depth_mm: 16.6,
    flipper_length_mm: 190,
    body_mass_g: "3.050,00",
    sex: "female",
    year: 2008
  },
  {
    id: 70,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 41.8,
    bill_depth_mm: 19.4,
    flipper_length_mm: 198,
    body_mass_g: "4.450,00",
    sex: "male",
    year: 2008
  },
  {
    id: 71,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 33.5,
    bill_depth_mm: 19,
    flipper_length_mm: 190,
    body_mass_g: "3.600,00",
    sex: "female",
    year: 2008
  },
  {
    id: 72,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 39.7,
    bill_depth_mm: 18.4,
    flipper_length_mm: 190,
    body_mass_g: "3.900,00",
    sex: "male",
    year: 2008
  },
  {
    id: 73,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 39.6,
    bill_depth_mm: 17.2,
    flipper_length_mm: 196,
    body_mass_g: "3.550,00",
    sex: "female",
    year: 2008
  },
  {
    id: 74,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 45.8,
    bill_depth_mm: 18.9,
    flipper_length_mm: 197,
    body_mass_g: "4.150,00",
    sex: "male",
    year: 2008
  },
  {
    id: 75,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 35.5,
    bill_depth_mm: 17.5,
    flipper_length_mm: 190,
    body_mass_g: "3.700,00",
    sex: "female",
    year: 2008
  },
  {
    id: 76,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 42.8,
    bill_depth_mm: 18.5,
    flipper_length_mm: 195,
    body_mass_g: "4.250,00",
    sex: "male",
    year: 2008
  },
  {
    id: 77,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 40.9,
    bill_depth_mm: 16.8,
    flipper_length_mm: 191,
    body_mass_g: "3.700,00",
    sex: "female",
    year: 2008
  },
  {
    id: 78,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 37.2,
    bill_depth_mm: 19.4,
    flipper_length_mm: 184,
    body_mass_g: "3.900,00",
    sex: "male",
    year: 2008
  },
  {
    id: 79,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 36.2,
    bill_depth_mm: 16.1,
    flipper_length_mm: 187,
    body_mass_g: "3.550,00",
    sex: "female",
    year: 2008
  },
  {
    id: 80,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 42.1,
    bill_depth_mm: 19.1,
    flipper_length_mm: 195,
    body_mass_g: "4.000,00",
    sex: "male",
    year: 2008
  },
  {
    id: 81,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 34.6,
    bill_depth_mm: 17.2,
    flipper_length_mm: 189,
    body_mass_g: "3.200,00",
    sex: "female",
    year: 2008
  },
  {
    id: 82,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 42.9,
    bill_depth_mm: 17.6,
    flipper_length_mm: 196,
    body_mass_g: "4.700,00",
    sex: "male",
    year: 2008
  },
  {
    id: 83,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 36.7,
    bill_depth_mm: 18.8,
    flipper_length_mm: 187,
    body_mass_g: "3.800,00",
    sex: "female",
    year: 2008
  },
  {
    id: 84,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 35.1,
    bill_depth_mm: 19.4,
    flipper_length_mm: 193,
    body_mass_g: "4.200,00",
    sex: "male",
    year: 2008
  },
  {
    id: 85,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 37.3,
    bill_depth_mm: 17.8,
    flipper_length_mm: 191,
    body_mass_g: "3.350,00",
    sex: "female",
    year: 2008
  },
  {
    id: 86,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 41.3,
    bill_depth_mm: 20.3,
    flipper_length_mm: 194,
    body_mass_g: "3.550,00",
    sex: "male",
    year: 2008
  },
  {
    id: 87,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 36.3,
    bill_depth_mm: 19.5,
    flipper_length_mm: 190,
    body_mass_g: "3.800,00",
    sex: "male",
    year: 2008
  },
  {
    id: 88,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 36.9,
    bill_depth_mm: 18.6,
    flipper_length_mm: 189,
    body_mass_g: "3.500,00",
    sex: "female",
    year: 2008
  },
  {
    id: 89,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 38.3,
    bill_depth_mm: 19.2,
    flipper_length_mm: 189,
    body_mass_g: "3.950,00",
    sex: "male",
    year: 2008
  },
  {
    id: 90,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 38.9,
    bill_depth_mm: 18.8,
    flipper_length_mm: 190,
    body_mass_g: "3.600,00",
    sex: "female",
    year: 2008
  },
  {
    id: 91,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 35.7,
    bill_depth_mm: 18,
    flipper_length_mm: 202,
    body_mass_g: "3.550,00",
    sex: "female",
    year: 2008
  },
  {
    id: 92,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 41.1,
    bill_depth_mm: 18.1,
    flipper_length_mm: 205,
    body_mass_g: "4.300,00",
    sex: "male",
    year: 2008
  },
  {
    id: 93,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 34,
    bill_depth_mm: 17.1,
    flipper_length_mm: 185,
    body_mass_g: "3.400,00",
    sex: "female",
    year: 2008
  },
  {
    id: 94,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 39.6,
    bill_depth_mm: 18.1,
    flipper_length_mm: 186,
    body_mass_g: "4.450,00",
    sex: "male",
    year: 2008
  },
  {
    id: 95,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 36.2,
    bill_depth_mm: 17.3,
    flipper_length_mm: 187,
    body_mass_g: "3.300,00",
    sex: "female",
    year: 2008
  },
  {
    id: 96,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 40.8,
    bill_depth_mm: 18.9,
    flipper_length_mm: 208,
    body_mass_g: "4.300,00",
    sex: "male",
    year: 2008
  },
  {
    id: 97,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 38.1,
    bill_depth_mm: 18.6,
    flipper_length_mm: 190,
    body_mass_g: "3.700,00",
    sex: "female",
    year: 2008
  },
  {
    id: 98,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 40.3,
    bill_depth_mm: 18.5,
    flipper_length_mm: 196,
    body_mass_g: "4.350,00",
    sex: "male",
    year: 2008
  },
  {
    id: 99,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 33.1,
    bill_depth_mm: 16.1,
    flipper_length_mm: 178,
    body_mass_g: "2.900,00",
    sex: "female",
    year: 2008
  },
  {
    id: 100,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 43.2,
    bill_depth_mm: 18.5,
    flipper_length_mm: 192,
    body_mass_g: "4.100,00",
    sex: "male",
    year: 2008
  },
  {
    id: 101,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 35,
    bill_depth_mm: 17.9,
    flipper_length_mm: 192,
    body_mass_g: "3.725,00",
    sex: "female",
    year: 2009
  },
  {
    id: 102,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 41,
    bill_depth_mm: 20,
    flipper_length_mm: 203,
    body_mass_g: "4.725,00",
    sex: "male",
    year: 2009
  },
  {
    id: 103,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 37.7,
    bill_depth_mm: 16,
    flipper_length_mm: 183,
    body_mass_g: "3.075,00",
    sex: "female",
    year: 2009
  },
  {
    id: 104,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 37.8,
    bill_depth_mm: 20,
    flipper_length_mm: 190,
    body_mass_g: "4.250,00",
    sex: "male",
    year: 2009
  },
  {
    id: 105,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 37.9,
    bill_depth_mm: 18.6,
    flipper_length_mm: 193,
    body_mass_g: "2.925,00",
    sex: "female",
    year: 2009
  },
  {
    id: 106,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 39.7,
    bill_depth_mm: 18.9,
    flipper_length_mm: 184,
    body_mass_g: "3.550,00",
    sex: "male",
    year: 2009
  },
  {
    id: 107,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 38.6,
    bill_depth_mm: 17.2,
    flipper_length_mm: 199,
    body_mass_g: "3.750,00",
    sex: "female",
    year: 2009
  },
  {
    id: 108,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 38.2,
    bill_depth_mm: 20,
    flipper_length_mm: 190,
    body_mass_g: "3.900,00",
    sex: "male",
    year: 2009
  },
  {
    id: 109,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 38.1,
    bill_depth_mm: 17,
    flipper_length_mm: 181,
    body_mass_g: "3.175,00",
    sex: "female",
    year: 2009
  },
  {
    id: 110,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 43.2,
    bill_depth_mm: 19,
    flipper_length_mm: 197,
    body_mass_g: "4.775,00",
    sex: "male",
    year: 2009
  },
  {
    id: 111,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 38.1,
    bill_depth_mm: 16.5,
    flipper_length_mm: 198,
    body_mass_g: "3.825,00",
    sex: "female",
    year: 2009
  },
  {
    id: 112,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 45.6,
    bill_depth_mm: 20.3,
    flipper_length_mm: 191,
    body_mass_g: "4.600,00",
    sex: "male",
    year: 2009
  },
  {
    id: 113,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 39.7,
    bill_depth_mm: 17.7,
    flipper_length_mm: 193,
    body_mass_g: "3.200,00",
    sex: "female",
    year: 2009
  },
  {
    id: 114,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 42.2,
    bill_depth_mm: 19.5,
    flipper_length_mm: 197,
    body_mass_g: "4.275,00",
    sex: "male",
    year: 2009
  },
  {
    id: 115,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 39.6,
    bill_depth_mm: 20.7,
    flipper_length_mm: 191,
    body_mass_g: "3.900,00",
    sex: "female",
    year: 2009
  },
  {
    id: 116,
   species: "Monumen Nasional",
   island: "Biscoe",
    bill_length_mm: 42.7,
    bill_depth_mm: 18.3,
    flipper_length_mm: 196,
    body_mass_g: "4.075,00",
    sex: "male",
    year: 2009
  },
  {
    id: 117,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 38.6,
    bill_depth_mm: 17,
    flipper_length_mm: 188,
    body_mass_g: "2.900,00",
    sex: "female",
    year: 2009
  },
  {
    id: 118,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 37.3,
    bill_depth_mm: 20.5,
    flipper_length_mm: 199,
    body_mass_g: "3.775,00",
    sex: "male",
    year: 2009
  },
  {
    id: 119,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 35.7,
    bill_depth_mm: 17,
    flipper_length_mm: 189,
    body_mass_g: "3.350,00",
    sex: "female",
    year: 2009
  },
  {
    id: 120,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 41.1,
    bill_depth_mm: 18.6,
    flipper_length_mm: 189,
    body_mass_g: "3.325,00",
    sex: "male",
    year: 2009
  },
  {
    id: 121,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 36.2,
    bill_depth_mm: 17.2,
    flipper_length_mm: 187,
    body_mass_g: "3.150,00",
    sex: "female",
    year: 2009
  },
  {
    id: 122,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 37.7,
    bill_depth_mm: 19.8,
    flipper_length_mm: 198,
    body_mass_g: "3.500,00",
    sex: "male",
    year: 2009
  },
  {
    id: 123,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 40.2,
    bill_depth_mm: 17,
    flipper_length_mm: 176,
    body_mass_g: "3.450,00",
    sex: "female",
    year: 2009
  },
  {
    id: 124,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 41.4,
    bill_depth_mm: 18.5,
    flipper_length_mm: 202,
    body_mass_g: "3.875,00",
    sex: "male",
    year: 2009
  },
  {
    id: 125,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 35.2,
    bill_depth_mm: 15.9,
    flipper_length_mm: 186,
    body_mass_g: "3.050,00",
    sex: "female",
    year: 2009
  },
  {
    id: 126,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 40.6,
    bill_depth_mm: 19,
    flipper_length_mm: 199,
    body_mass_g: "4.000,00",
    sex: "male",
    year: 2009
  },
  {
    id: 127,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 38.8,
    bill_depth_mm: 17.6,
    flipper_length_mm: 191,
    body_mass_g: "3.275,00",
    sex: "female",
    year: 2009
  },
  {
    id: 128,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 41.5,
    bill_depth_mm: 18.3,
    flipper_length_mm: 195,
    body_mass_g: "4.300,00",
    sex: "male",
    year: 2009
  },
  {
    id: 129,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 39,
    bill_depth_mm: 17.1,
    flipper_length_mm: 191,
    body_mass_g: "3.050,00",
    sex: "female",
    year: 2009
  },
  {
    id: 130,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 44.1,
    bill_depth_mm: 18,
    flipper_length_mm: 210,
    body_mass_g: "4.000,00",
    sex: "male",
    year: 2009
  },
  {
    id: 131,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 38.5,
    bill_depth_mm: 17.9,
    flipper_length_mm: 190,
    body_mass_g: "3.325,00",
    sex: "female",
    year: 2009
  },
  {
    id: 132,
   species: "Monumen Nasional",
   island: "Torgersen",
    bill_length_mm: 43.1,
    bill_depth_mm: 19.2,
    flipper_length_mm: 197,
    body_mass_g: "3.500,00",
    sex: "male",
    year: 2009
  },
  {
    id: 133,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 36.8,
    bill_depth_mm: 18.5,
    flipper_length_mm: 193,
    body_mass_g: "3.500,00",
    sex: "female",
    year: 2009
  },
  {
    id: 134,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 37.5,
    bill_depth_mm: 18.5,
    flipper_length_mm: 199,
    body_mass_g: "4.475,00",
    sex: "male",
    year: 2009
  },
  {
    id: 135,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 38.1,
    bill_depth_mm: 17.6,
    flipper_length_mm: 187,
    body_mass_g: "3.425,00",
    sex: "female",
    year: 2009
  },
  {
    id: 136,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 41.1,
    bill_depth_mm: 17.5,
    flipper_length_mm: 190,
    body_mass_g: "3.900,00",
    sex: "male",
    year: 2009
  },
  {
    id: 137,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 35.6,
    bill_depth_mm: 17.5,
    flipper_length_mm: 191,
    body_mass_g: "3.175,00",
    sex: "female",
    year: 2009
  },
  {
    id: 138,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 40.2,
    bill_depth_mm: 20.1,
    flipper_length_mm: 200,
    body_mass_g: "3.975,00",
    sex: "male",
    year: 2009
  },
  {
    id: 139,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 37,
    bill_depth_mm: 16.5,
    flipper_length_mm: 185,
    body_mass_g: "3.400,00",
    sex: "female",
    year: 2009
  },
  {
    id: 140,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 39.7,
    bill_depth_mm: 17.9,
    flipper_length_mm: 193,
    body_mass_g: "4.250,00",
    sex: "male",
    year: 2009
  },
  {
    id: 141,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 40.2,
    bill_depth_mm: 17.1,
    flipper_length_mm: 193,
    body_mass_g: "3.400,00",
    sex: "female",
    year: 2009
  },
  {
    id: 142,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 40.6,
    bill_depth_mm: 17.2,
    flipper_length_mm: 187,
    body_mass_g: "3.475,00",
    sex: "male",
    year: 2009
  },
  {
    id: 143,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 32.1,
    bill_depth_mm: 15.5,
    flipper_length_mm: 188,
    body_mass_g: "3.050,00",
    sex: "female",
    year: 2009
  },
  {
    id: 144,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 40.7,
    bill_depth_mm: 17,
    flipper_length_mm: 190,
    body_mass_g: "3.725,00",
    sex: "male",
    year: 2009
  },
  {
    id: 145,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 37.3,
    bill_depth_mm: 16.8,
    flipper_length_mm: 192,
    body_mass_g: "3.000,00",
    sex: "female",
    year: 2009
  },
  {
    id: 146,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 39,
    bill_depth_mm: 18.7,
    flipper_length_mm: 185,
    body_mass_g: "3.650,00",
    sex: "male",
    year: 2009
  },
  {
    id: 147,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 39.2,
    bill_depth_mm: 18.6,
    flipper_length_mm: 190,
    body_mass_g: "4.250,00",
    sex: "male",
    year: 2009
  },
  {
    id: 148,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 36.6,
    bill_depth_mm: 18.4,
    flipper_length_mm: 184,
    body_mass_g: "3.475,00",
    sex: "female",
    year: 2009
  },
  {
    id: 149,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 36,
    bill_depth_mm: 17.8,
    flipper_length_mm: 195,
    body_mass_g: "3.450,00",
    sex: "female",
    year: 2009
  },
  {
    id: 150,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 37.8,
    bill_depth_mm: 18.1,
    flipper_length_mm: 193,
    body_mass_g: "3.750,00",
    sex: "male",
    year: 2009
  },
  {
    id: 151,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 36,
    bill_depth_mm: 17.1,
    flipper_length_mm: 187,
    body_mass_g: "3.700,00",
    sex: "female",
    year: 2009
  },
  {
    id: 152,
   species: "Monumen Nasional",
   island: "Dream",
    bill_length_mm: 41.5,
    bill_depth_mm: 18.5,
    flipper_length_mm: 201,
    body_mass_g: "4.000,00",
    sex: "male",
    year: 2009
  },
  {
    id: 153,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.1,
    bill_depth_mm: 13.2,
    flipper_length_mm: 211,
    body_mass_g: "4.500,00",
    sex: "female",
    year: 2007
  },
  {
    id: 154,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50,
    bill_depth_mm: 16.3,
    flipper_length_mm: 230,
    body_mass_g: "5.700,00",
    sex: "male",
    year: 2007
  },
  {
    id: 155,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.7,
    bill_depth_mm: 14.1,
    flipper_length_mm: 210,
    body_mass_g: "4.450,00",
    sex: "female",
    year: 2007
  },
  {
    id: 156,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50,
    bill_depth_mm: 15.2,
    flipper_length_mm: 218,
    body_mass_g: "5.700,00",
    sex: "male",
    year: 2007
  },
  {
    id: 157,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 47.6,
    bill_depth_mm: 14.5,
    flipper_length_mm: 215,
    body_mass_g: "5.400,00",
    sex: "male",
    year: 2007
  },
  {
    id: 158,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.5,
    bill_depth_mm: 13.5,
    flipper_length_mm: 210,
    body_mass_g: "4.550,00",
    sex: "female",
    year: 2007
  },
  {
    id: 159,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.4,
    bill_depth_mm: 14.6,
    flipper_length_mm: 211,
    body_mass_g: "4.800,00",
    sex: "female",
    year: 2007
  },
  {
    id: 160,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.7,
    bill_depth_mm: 15.3,
    flipper_length_mm: 219,
    body_mass_g: "5.200,00",
    sex: "male",
    year: 2007
  },
  {
    id: 161,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 43.3,
    bill_depth_mm: 13.4,
    flipper_length_mm: 209,
    body_mass_g: "4.400,00",
    sex: "female",
    year: 2007
  },
  {
    id: 162,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.8,
    bill_depth_mm: 15.4,
    flipper_length_mm: 215,
    body_mass_g: "5.150,00",
    sex: "male",
    year: 2007
  },
  {
    id: 163,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 40.9,
    bill_depth_mm: 13.7,
    flipper_length_mm: 214,
    body_mass_g: "4.650,00",
    sex: "female",
    year: 2007
  },
  {
    id: 164,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49,
    bill_depth_mm: 16.1,
    flipper_length_mm: 216,
    body_mass_g: "5.550,00",
    sex: "male",
    year: 2007
  },
  {
    id: 165,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.5,
    bill_depth_mm: 13.7,
    flipper_length_mm: 214,
    body_mass_g: "4.650,00",
    sex: "female",
    year: 2007
  },
  {
    id: 166,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.4,
    bill_depth_mm: 14.6,
    flipper_length_mm: 213,
    body_mass_g: "5.850,00",
    sex: "male",
    year: 2007
  },
  {
    id: 167,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.8,
    bill_depth_mm: 14.6,
    flipper_length_mm: 210,
    body_mass_g: "4.200,00",
    sex: "female",
    year: 2007
  },
  {
    id: 168,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.3,
    bill_depth_mm: 15.7,
    flipper_length_mm: 217,
    body_mass_g: "5.850,00",
    sex: "male",
    year: 2007
  },
  {
    id: 169,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 42,
    bill_depth_mm: 13.5,
    flipper_length_mm: 210,
    body_mass_g: "4.150,00",
    sex: "female",
    year: 2007
  },
  {
    id: 170,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.2,
    bill_depth_mm: 15.2,
    flipper_length_mm: 221,
    body_mass_g: "6.300,00",
    sex: "male",
    year: 2007
  },
  {
    id: 171,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.2,
    bill_depth_mm: 14.5,
    flipper_length_mm: 209,
    body_mass_g: "4.800,00",
    sex: "female",
    year: 2007
  },
  {
    id: 172,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.7,
    bill_depth_mm: 15.1,
    flipper_length_mm: 222,
    body_mass_g: "5.350,00",
    sex: "male",
    year: 2007
  },
  {
    id: 173,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50.2,
    bill_depth_mm: 14.3,
    flipper_length_mm: 218,
    body_mass_g: "5.700,00",
    sex: "male",
    year: 2007
  },
  {
    id: 174,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.1,
    bill_depth_mm: 14.5,
    flipper_length_mm: 215,
    body_mass_g: "5.000,00",
    sex: "female",
    year: 2007
  },
  {
    id: 175,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.5,
    bill_depth_mm: 14.5,
    flipper_length_mm: 213,
    body_mass_g: "4.400,00",
    sex: "female",
    year: 2007
  },
  {
    id: 176,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.3,
    bill_depth_mm: 15.8,
    flipper_length_mm: 215,
    body_mass_g: "5.050,00",
    sex: "male",
    year: 2007
  },
  {
    id: 177,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 42.9,
    bill_depth_mm: 13.1,
    flipper_length_mm: 215,
    body_mass_g: "5.000,00",
    sex: "female",
    year: 2007
  },
  {
    id: 178,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.1,
    bill_depth_mm: 15.1,
    flipper_length_mm: 215,
    body_mass_g: "5.100,00",
    sex: "male",
    year: 2007
  },
  {
    id: 179,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 44.5,
    bill_depth_mm: 14.3,
    flipper_length_mm: 216,
    body_mass_g: "4.100,00",
    sex: "NA",
    year: 2007
  },
  {
    id: 180,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 47.8,
    bill_depth_mm: 15,
    flipper_length_mm: 215,
    body_mass_g: "5.650,00",
    sex: "male",
    year: 2007
  },
  {
    id: 181,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.2,
    bill_depth_mm: 14.3,
    flipper_length_mm: 210,
    body_mass_g: "4.600,00",
    sex: "female",
    year: 2007
  },
  {
    id: 182,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50,
    bill_depth_mm: 15.3,
    flipper_length_mm: 220,
    body_mass_g: "5.550,00",
    sex: "male",
    year: 2007
  },
  {
    id: 183,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 47.3,
    bill_depth_mm: 15.3,
    flipper_length_mm: 222,
    body_mass_g: "5.250,00",
    sex: "male",
    year: 2007
  },
  {
    id: 184,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 42.8,
    bill_depth_mm: 14.2,
    flipper_length_mm: 209,
    body_mass_g: "4.700,00",
    sex: "female",
    year: 2007
  },
  {
    id: 185,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.1,
    bill_depth_mm: 14.5,
    flipper_length_mm: 207,
    body_mass_g: "5.050,00",
    sex: "female",
    year: 2007
  },
  {
    id: 186,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 59.6,
    bill_depth_mm: 17,
    flipper_length_mm: 230,
    body_mass_g: "6.050,00",
    sex: "male",
    year: 2007
  },
  {
    id: 187,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.1,
    bill_depth_mm: 14.8,
    flipper_length_mm: 220,
    body_mass_g: "5.150,00",
    sex: "female",
    year: 2008
  },
  {
    id: 188,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.4,
    bill_depth_mm: 16.3,
    flipper_length_mm: 220,
    body_mass_g: "5.400,00",
    sex: "male",
    year: 2008
  },
  {
    id: 189,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 42.6,
    bill_depth_mm: 13.7,
    flipper_length_mm: 213,
    body_mass_g: "4.950,00",
    sex: "female",
    year: 2008
  },
  {
    id: 190,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 44.4,
    bill_depth_mm: 17.3,
    flipper_length_mm: 219,
    body_mass_g: "5.250,00",
    sex: "male",
    year: 2008
  },
  {
    id: 191,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 44,
    bill_depth_mm: 13.6,
    flipper_length_mm: 208,
    body_mass_g: "4.350,00",
    sex: "female",
    year: 2008
  },
  {
    id: 192,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.7,
    bill_depth_mm: 15.7,
    flipper_length_mm: 208,
    body_mass_g: "5.350,00",
    sex: "male",
    year: 2008
  },
  {
    id: 193,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 42.7,
    bill_depth_mm: 13.7,
    flipper_length_mm: 208,
    body_mass_g: "3.950,00",
    sex: "female",
    year: 2008
  },
  {
    id: 194,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.6,
    bill_depth_mm: 16,
    flipper_length_mm: 225,
    body_mass_g: "5.700,00",
    sex: "male",
    year: 2008
  },
  {
    id: 195,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.3,
    bill_depth_mm: 13.7,
    flipper_length_mm: 210,
    body_mass_g: "4.300,00",
    sex: "female",
    year: 2008
  },
  {
    id: 196,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.6,
    bill_depth_mm: 15,
    flipper_length_mm: 216,
    body_mass_g: "4.750,00",
    sex: "male",
    year: 2008
  },
  {
    id: 197,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50.5,
    bill_depth_mm: 15.9,
    flipper_length_mm: 222,
    body_mass_g: "5.550,00",
    sex: "male",
    year: 2008
  },
  {
    id: 198,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 43.6,
    bill_depth_mm: 13.9,
    flipper_length_mm: 217,
    body_mass_g: "4.900,00",
    sex: "female",
    year: 2008
  },
  {
    id: 199,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.5,
    bill_depth_mm: 13.9,
    flipper_length_mm: 210,
    body_mass_g: "4.200,00",
    sex: "female",
    year: 2008
  },
  {
    id: 200,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50.5,
    bill_depth_mm: 15.9,
    flipper_length_mm: 225,
    body_mass_g: "5.400,00",
    sex: "male",
    year: 2008
  },
  {
    id: 201,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 44.9,
    bill_depth_mm: 13.3,
    flipper_length_mm: 213,
    body_mass_g: "5.100,00",
    sex: "female",
    year: 2008
  },
  {
    id: 202,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.2,
    bill_depth_mm: 15.8,
    flipper_length_mm: 215,
    body_mass_g: "5.300,00",
    sex: "male",
    year: 2008
  },
  {
    id: 203,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.6,
    bill_depth_mm: 14.2,
    flipper_length_mm: 210,
    body_mass_g: "4.850,00",
    sex: "female",
    year: 2008
  },
  {
    id: 204,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.5,
    bill_depth_mm: 14.1,
    flipper_length_mm: 220,
    body_mass_g: "5.300,00",
    sex: "male",
    year: 2008
  },
  {
    id: 205,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.1,
    bill_depth_mm: 14.4,
    flipper_length_mm: 210,
    body_mass_g: "4.400,00",
    sex: "female",
    year: 2008
  },
  {
    id: 206,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50.1,
    bill_depth_mm: 15,
    flipper_length_mm: 225,
    body_mass_g: "5.000,00",
    sex: "male",
    year: 2008
  },
  {
    id: 207,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.5,
    bill_depth_mm: 14.4,
    flipper_length_mm: 217,
    body_mass_g: "4.900,00",
    sex: "female",
    year: 2008
  },
  {
    id: 208,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45,
    bill_depth_mm: 15.4,
    flipper_length_mm: 220,
    body_mass_g: "5.050,00",
    sex: "male",
    year: 2008
  },
  {
    id: 209,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 43.8,
    bill_depth_mm: 13.9,
    flipper_length_mm: 208,
    body_mass_g: "4.300,00",
    sex: "female",
    year: 2008
  },
  {
    id: 210,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.5,
    bill_depth_mm: 15,
    flipper_length_mm: 220,
    body_mass_g: "5.000,00",
    sex: "male",
    year: 2008
  },
  {
    id: 211,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 43.2,
    bill_depth_mm: 14.5,
    flipper_length_mm: 208,
    body_mass_g: "4.450,00",
    sex: "female",
    year: 2008
  },
  {
    id: 212,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50.4,
    bill_depth_mm: 15.3,
    flipper_length_mm: 224,
    body_mass_g: "5.550,00",
    sex: "male",
    year: 2008
  },
  {
    id: 213,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.3,
    bill_depth_mm: 13.8,
    flipper_length_mm: 208,
    body_mass_g: "4.200,00",
    sex: "female",
    year: 2008
  },
  {
    id: 214,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.2,
    bill_depth_mm: 14.9,
    flipper_length_mm: 221,
    body_mass_g: "5.300,00",
    sex: "male",
    year: 2008
  },
  {
    id: 215,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.7,
    bill_depth_mm: 13.9,
    flipper_length_mm: 214,
    body_mass_g: "4.400,00",
    sex: "female",
    year: 2008
  },
  {
    id: 216,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 54.3,
    bill_depth_mm: 15.7,
    flipper_length_mm: 231,
    body_mass_g: "5.650,00",
    sex: "male",
    year: 2008
  },
  {
    id: 217,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.8,
    bill_depth_mm: 14.2,
    flipper_length_mm: 219,
    body_mass_g: "4.700,00",
    sex: "female",
    year: 2008
  },
  {
    id: 218,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.8,
    bill_depth_mm: 16.8,
    flipper_length_mm: 230,
    body_mass_g: "5.700,00",
    sex: "male",
    year: 2008
  },
  {
    id: 219,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.2,
    bill_depth_mm: 14.4,
    flipper_length_mm: 214,
    body_mass_g: "4.650,00",
    sex: "NA",
    year: 2008
  },
  {
    id: 220,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.5,
    bill_depth_mm: 16.2,
    flipper_length_mm: 229,
    body_mass_g: "5.800,00",
    sex: "male",
    year: 2008
  },
  {
    id: 221,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 43.5,
    bill_depth_mm: 14.2,
    flipper_length_mm: 220,
    body_mass_g: "4.700,00",
    sex: "female",
    year: 2008
  },
  {
    id: 222,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50.7,
    bill_depth_mm: 15,
    flipper_length_mm: 223,
    body_mass_g: "5.550,00",
    sex: "male",
    year: 2008
  },
  {
    id: 223,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 47.7,
    bill_depth_mm: 15,
    flipper_length_mm: 216,
    body_mass_g: "4.750,00",
    sex: "female",
    year: 2008
  },
  {
    id: 224,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.4,
    bill_depth_mm: 15.6,
    flipper_length_mm: 221,
    body_mass_g: "5.000,00",
    sex: "male",
    year: 2008
  },
  {
    id: 225,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.2,
    bill_depth_mm: 15.6,
    flipper_length_mm: 221,
    body_mass_g: "5.100,00",
    sex: "male",
    year: 2008
  },
  {
    id: 226,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.5,
    bill_depth_mm: 14.8,
    flipper_length_mm: 217,
    body_mass_g: "5.200,00",
    sex: "female",
    year: 2008
  },
  {
    id: 227,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.4,
    bill_depth_mm: 15,
    flipper_length_mm: 216,
    body_mass_g: "4.700,00",
    sex: "female",
    year: 2008
  },
  {
    id: 228,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.6,
    bill_depth_mm: 16,
    flipper_length_mm: 230,
    body_mass_g: "5.800,00",
    sex: "male",
    year: 2008
  },
  {
    id: 229,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 47.5,
    bill_depth_mm: 14.2,
    flipper_length_mm: 209,
    body_mass_g: "4.600,00",
    sex: "female",
    year: 2008
  },
  {
    id: 230,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 51.1,
    bill_depth_mm: 16.3,
    flipper_length_mm: 220,
    body_mass_g: "6.000,00",
    sex: "male",
    year: 2008
  },
  {
    id: 231,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.2,
    bill_depth_mm: 13.8,
    flipper_length_mm: 215,
    body_mass_g: "4.750,00",
    sex: "female",
    year: 2008
  },
  {
    id: 232,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.2,
    bill_depth_mm: 16.4,
    flipper_length_mm: 223,
    body_mass_g: "5.950,00",
    sex: "male",
    year: 2008
  },
  {
    id: 233,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.1,
    bill_depth_mm: 14.5,
    flipper_length_mm: 212,
    body_mass_g: "4.625,00",
    sex: "female",
    year: 2009
  },
  {
    id: 234,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 52.5,
    bill_depth_mm: 15.6,
    flipper_length_mm: 221,
    body_mass_g: "5.450,00",
    sex: "male",
    year: 2009
  },
  {
    id: 235,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 47.4,
    bill_depth_mm: 14.6,
    flipper_length_mm: 212,
    body_mass_g: "4.725,00",
    sex: "female",
    year: 2009
  },
  {
    id: 236,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50,
    bill_depth_mm: 15.9,
    flipper_length_mm: 224,
    body_mass_g: "5.350,00",
    sex: "male",
    year: 2009
  },
  {
    id: 237,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 44.9,
    bill_depth_mm: 13.8,
    flipper_length_mm: 212,
    body_mass_g: "4.750,00",
    sex: "female",
    year: 2009
  },
  {
    id: 238,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50.8,
    bill_depth_mm: 17.3,
    flipper_length_mm: 228,
    body_mass_g: "5.600,00",
    sex: "male",
    year: 2009
  },
  {
    id: 239,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 43.4,
    bill_depth_mm: 14.4,
    flipper_length_mm: 218,
    body_mass_g: "4.600,00",
    sex: "female",
    year: 2009
  },
  {
    id: 240,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 51.3,
    bill_depth_mm: 14.2,
    flipper_length_mm: 218,
    body_mass_g: "5.300,00",
    sex: "male",
    year: 2009
  },
  {
    id: 241,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 47.5,
    bill_depth_mm: 14,
    flipper_length_mm: 212,
    body_mass_g: "4.875,00",
    sex: "female",
    year: 2009
  },
  {
    id: 242,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 52.1,
    bill_depth_mm: 17,
    flipper_length_mm: 230,
    body_mass_g: "5.550,00",
    sex: "male",
    year: 2009
  },
  {
    id: 243,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 47.5,
    bill_depth_mm: 15,
    flipper_length_mm: 218,
    body_mass_g: "4.950,00",
    sex: "female",
    year: 2009
  },
  {
    id: 244,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 52.2,
    bill_depth_mm: 17.1,
    flipper_length_mm: 228,
    body_mass_g: "5.400,00",
    sex: "male",
    year: 2009
  },
  {
    id: 245,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.5,
    bill_depth_mm: 14.5,
    flipper_length_mm: 212,
    body_mass_g: "4.750,00",
    sex: "female",
    year: 2009
  },
  {
    id: 246,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.5,
    bill_depth_mm: 16.1,
    flipper_length_mm: 224,
    body_mass_g: "5.650,00",
    sex: "male",
    year: 2009
  },
  {
    id: 247,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 44.5,
    bill_depth_mm: 14.7,
    flipper_length_mm: 214,
    body_mass_g: "4.850,00",
    sex: "female",
    year: 2009
  },
  {
    id: 248,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50.8,
    bill_depth_mm: 15.7,
    flipper_length_mm: 226,
    body_mass_g: "5.200,00",
    sex: "male",
    year: 2009
  },
  {
    id: 249,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.4,
    bill_depth_mm: 15.8,
    flipper_length_mm: 216,
    body_mass_g: "4.925,00",
    sex: "male",
    year: 2009
  },
  {
    id: 250,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.9,
    bill_depth_mm: 14.6,
    flipper_length_mm: 222,
    body_mass_g: "4.875,00",
    sex: "female",
    year: 2009
  },
  {
    id: 251,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.4,
    bill_depth_mm: 14.4,
    flipper_length_mm: 203,
    body_mass_g: "4.625,00",
    sex: "female",
    year: 2009
  },
  {
    id: 252,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 51.1,
    bill_depth_mm: 16.5,
    flipper_length_mm: 225,
    body_mass_g: "5.250,00",
    sex: "male",
    year: 2009
  },
  {
    id: 253,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.5,
    bill_depth_mm: 15,
    flipper_length_mm: 219,
    body_mass_g: "4.850,00",
    sex: "female",
    year: 2009
  },
  {
    id: 254,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 55.9,
    bill_depth_mm: 17,
    flipper_length_mm: 228,
    body_mass_g: "5.600,00",
    sex: "male",
    year: 2009
  },
  {
    id: 255,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 47.2,
    bill_depth_mm: 15.5,
    flipper_length_mm: 215,
    body_mass_g: "4.975,00",
    sex: "female",
    year: 2009
  },
  {
    id: 256,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.1,
    bill_depth_mm: 15,
    flipper_length_mm: 228,
    body_mass_g: "5.500,00",
    sex: "male",
    year: 2009
  },
  {
    id: 257,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 47.3,
    bill_depth_mm: 13.8,
    flipper_length_mm: 216,
    body_mass_g: "4.725,00",
    sex: "NA",
    year: 2009
  },
  {
    id: 258,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.8,
    bill_depth_mm: 16.1,
    flipper_length_mm: 215,
    body_mass_g: "5.500,00",
    sex: "male",
    year: 2009
  },
  {
    id: 259,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 41.7,
    bill_depth_mm: 14.7,
    flipper_length_mm: 210,
    body_mass_g: "4.700,00",
    sex: "female",
    year: 2009
  },
  {
    id: 260,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 53.4,
    bill_depth_mm: 15.8,
    flipper_length_mm: 219,
    body_mass_g: "5.500,00",
    sex: "male",
    year: 2009
  },
  {
    id: 261,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 43.3,
    bill_depth_mm: 14,
    flipper_length_mm: 208,
    body_mass_g: "4.575,00",
    sex: "female",
    year: 2009
  },
  {
    id: 262,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.1,
    bill_depth_mm: 15.1,
    flipper_length_mm: 209,
    body_mass_g: "5.500,00",
    sex: "male",
    year: 2009
  },
  {
    id: 263,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50.5,
    bill_depth_mm: 15.2,
    flipper_length_mm: 216,
    body_mass_g: "5.000,00",
    sex: "female",
    year: 2009
  },
  {
    id: 264,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.8,
    bill_depth_mm: 15.9,
    flipper_length_mm: 229,
    body_mass_g: "5.950,00",
    sex: "male",
    year: 2009
  },
  {
    id: 265,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 43.5,
    bill_depth_mm: 15.2,
    flipper_length_mm: 213,
    body_mass_g: "4.650,00",
    sex: "female",
    year: 2009
  },
  {
    id: 266,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 51.5,
    bill_depth_mm: 16.3,
    flipper_length_mm: 230,
    body_mass_g: "5.500,00",
    sex: "male",
    year: 2009
  },
  {
    id: 267,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.2,
    bill_depth_mm: 14.1,
    flipper_length_mm: 217,
    body_mass_g: "4.375,00",
    sex: "female",
    year: 2009
  },
  {
    id: 268,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 55.1,
    bill_depth_mm: 16,
    flipper_length_mm: 230,
    body_mass_g: "5.850,00",
    sex: "male",
    year: 2009
  },
  {
    id: 269,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 44.5,
    bill_depth_mm: 15.7,
    flipper_length_mm: 217,
    body_mass_g: "4.875,00",
    sex: "NA",
    year: 2009
  },
  {
    id: 270,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 48.8,
    bill_depth_mm: 16.2,
    flipper_length_mm: 222,
    body_mass_g: "6.000,00",
    sex: "male",
    year: 2009
  },
  {
    id: 271,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 47.2,
    bill_depth_mm: 13.7,
    flipper_length_mm: 214,
    body_mass_g: "4.925,00",
    sex: "female",
    year: 2009
  },
  {
    id: 272,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: "NA",
    bill_depth_mm: "NA",
    flipper_length_mm: "NA",
    body_mass_g: "NA",
    sex: "NA",
    year: 2009
  },
  {
    id: 273,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 46.8,
    bill_depth_mm: 14.3,
    flipper_length_mm: 215,
    body_mass_g: "4.850,00",
    sex: "female",
    year: 2009
  },
  {
    id: 274,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 50.4,
    bill_depth_mm: 15.7,
    flipper_length_mm: 222,
    body_mass_g: "5.750,00",
    sex: "male",
    year: 2009
  },
  {
    id: 275,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 45.2,
    bill_depth_mm: 14.8,
    flipper_length_mm: 212,
    body_mass_g: "5.200,00",
    sex: "female",
    year: 2009
  },
  {
    id: 276,
   species: "Dunia Fantasi",
   island: "Biscoe",
    bill_length_mm: 49.9,
    bill_depth_mm: 16.1,
    flipper_length_mm: 213,
    body_mass_g: "5.400,00",
    sex: "male",
    year: 2009
  },
  {
    id: 277,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 46.5,
    bill_depth_mm: 17.9,
    flipper_length_mm: 192,
    body_mass_g: "3.500,00",
    sex: "female",
    year: 2007
  },
  {
    id: 278,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50,
    bill_depth_mm: 19.5,
    flipper_length_mm: 196,
    body_mass_g: "3.900,00",
    sex: "male",
    year: 2007
  },
  {
    id: 279,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 51.3,
    bill_depth_mm: 19.2,
    flipper_length_mm: 193,
    body_mass_g: "3.650,00",
    sex: "male",
    year: 2007
  },
  {
    id: 280,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 45.4,
    bill_depth_mm: 18.7,
    flipper_length_mm: 188,
    body_mass_g: "3.525,00",
    sex: "female",
    year: 2007
  },
  {
    id: 281,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 52.7,
    bill_depth_mm: 19.8,
    flipper_length_mm: 197,
    body_mass_g: "3.725,00",
    sex: "male",
    year: 2007
  },
  {
    id: 282,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 45.2,
    bill_depth_mm: 17.8,
    flipper_length_mm: 198,
    body_mass_g: "3.950,00",
    sex: "female",
    year: 2007
  },
  {
    id: 283,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 46.1,
    bill_depth_mm: 18.2,
    flipper_length_mm: 178,
    body_mass_g: "3.250,00",
    sex: "female",
    year: 2007
  },
  {
    id: 284,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 51.3,
    bill_depth_mm: 18.2,
    flipper_length_mm: 197,
    body_mass_g: "3.750,00",
    sex: "male",
    year: 2007
  },
  {
    id: 285,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 46,
    bill_depth_mm: 18.9,
    flipper_length_mm: 195,
    body_mass_g: "4.150,00",
    sex: "female",
    year: 2007
  },
  {
    id: 286,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 51.3,
    bill_depth_mm: 19.9,
    flipper_length_mm: 198,
    body_mass_g: "3.700,00",
    sex: "male",
    year: 2007
  },
  {
    id: 287,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 46.6,
    bill_depth_mm: 17.8,
    flipper_length_mm: 193,
    body_mass_g: "3.800,00",
    sex: "female",
    year: 2007
  },
  {
    id: 288,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 51.7,
    bill_depth_mm: 20.3,
    flipper_length_mm: 194,
    body_mass_g: "3.775,00",
    sex: "male",
    year: 2007
  },
  {
    id: 289,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 47,
    bill_depth_mm: 17.3,
    flipper_length_mm: 185,
    body_mass_g: "3.700,00",
    sex: "female",
    year: 2007
  },
  {
    id: 290,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 52,
    bill_depth_mm: 18.1,
    flipper_length_mm: 201,
    body_mass_g: "4.050,00",
    sex: "male",
    year: 2007
  },
  {
    id: 291,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 45.9,
    bill_depth_mm: 17.1,
    flipper_length_mm: 190,
    body_mass_g: "3.575,00",
    sex: "female",
    year: 2007
  },
  {
    id: 292,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50.5,
    bill_depth_mm: 19.6,
    flipper_length_mm: 201,
    body_mass_g: "4.050,00",
    sex: "male",
    year: 2007
  },
  {
    id: 293,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50.3,
    bill_depth_mm: 20,
    flipper_length_mm: 197,
    body_mass_g: "3.300,00",
    sex: "male",
    year: 2007
  },
  {
    id: 294,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 58,
    bill_depth_mm: 17.8,
    flipper_length_mm: 181,
    body_mass_g: "3.700,00",
    sex: "female",
    year: 2007
  },
  {
    id: 295,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 46.4,
    bill_depth_mm: 18.6,
    flipper_length_mm: 190,
    body_mass_g: "3.450,00",
    sex: "female",
    year: 2007
  },
  {
    id: 296,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 49.2,
    bill_depth_mm: 18.2,
    flipper_length_mm: 195,
    body_mass_g: "4.400,00",
    sex: "male",
    year: 2007
  },
  {
    id: 297,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 42.4,
    bill_depth_mm: 17.3,
    flipper_length_mm: 181,
    body_mass_g: "3.600,00",
    sex: "female",
    year: 2007
  },
  {
    id: 298,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 48.5,
    bill_depth_mm: 17.5,
    flipper_length_mm: 191,
    body_mass_g: "3.400,00",
    sex: "male",
    year: 2007
  },
  {
    id: 299,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 43.2,
    bill_depth_mm: 16.6,
    flipper_length_mm: 187,
    body_mass_g: "2.900,00",
    sex: "female",
    year: 2007
  },
  {
    id: 300,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50.6,
    bill_depth_mm: 19.4,
    flipper_length_mm: 193,
    body_mass_g: "3.800,00",
    sex: "male",
    year: 2007
  },
  {
    id: 301,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 46.7,
    bill_depth_mm: 17.9,
    flipper_length_mm: 195,
    body_mass_g: "3.300,00",
    sex: "female",
    year: 2007
  },
  {
    id: 302,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 52,
    bill_depth_mm: 19,
    flipper_length_mm: 197,
    body_mass_g: "4.150,00",
    sex: "male",
    year: 2007
  },
  {
    id: 303,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50.5,
    bill_depth_mm: 18.4,
    flipper_length_mm: 200,
    body_mass_g: "3.400,00",
    sex: "female",
    year: 2008
  },
  {
    id: 304,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 49.5,
    bill_depth_mm: 19,
    flipper_length_mm: 200,
    body_mass_g: "3.800,00",
    sex: "male",
    year: 2008
  },
  {
    id: 305,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 46.4,
    bill_depth_mm: 17.8,
    flipper_length_mm: 191,
    body_mass_g: "3.700,00",
    sex: "female",
    year: 2008
  },
  {
    id: 306,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 52.8,
    bill_depth_mm: 20,
    flipper_length_mm: 205,
    body_mass_g: "4.550,00",
    sex: "male",
    year: 2008
  },
  {
    id: 307,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 40.9,
    bill_depth_mm: 16.6,
    flipper_length_mm: 187,
    body_mass_g: "3.200,00",
    sex: "female",
    year: 2008
  },
  {
    id: 308,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 54.2,
    bill_depth_mm: 20.8,
    flipper_length_mm: 201,
    body_mass_g: "4.300,00",
    sex: "male",
    year: 2008
  },
  {
    id: 309,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 42.5,
    bill_depth_mm: 16.7,
    flipper_length_mm: 187,
    body_mass_g: "3.350,00",
    sex: "female",
    year: 2008
  },
  {
    id: 310,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 51,
    bill_depth_mm: 18.8,
    flipper_length_mm: 203,
    body_mass_g: "4.100,00",
    sex: "male",
    year: 2008
  },
  {
    id: 311,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 49.7,
    bill_depth_mm: 18.6,
    flipper_length_mm: 195,
    body_mass_g: "3.600,00",
    sex: "male",
    year: 2008
  },
  {
    id: 312,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 47.5,
    bill_depth_mm: 16.8,
    flipper_length_mm: 199,
    body_mass_g: "3.900,00",
    sex: "female",
    year: 2008
  },
  {
    id: 313,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 47.6,
    bill_depth_mm: 18.3,
    flipper_length_mm: 195,
    body_mass_g: "3.850,00",
    sex: "female",
    year: 2008
  },
  {
    id: 314,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 52,
    bill_depth_mm: 20.7,
    flipper_length_mm: 210,
    body_mass_g: "4.800,00",
    sex: "male",
    year: 2008
  },
  {
    id: 315,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 46.9,
    bill_depth_mm: 16.6,
    flipper_length_mm: 192,
    body_mass_g: "2.700,00",
    sex: "female",
    year: 2008
  },
  {
    id: 316,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 53.5,
    bill_depth_mm: 19.9,
    flipper_length_mm: 205,
    body_mass_g: "4.500,00",
    sex: "male",
    year: 2008
  },
  {
    id: 317,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 49,
    bill_depth_mm: 19.5,
    flipper_length_mm: 210,
    body_mass_g: "3.950,00",
    sex: "male",
    year: 2008
  },
  {
    id: 318,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 46.2,
    bill_depth_mm: 17.5,
    flipper_length_mm: 187,
    body_mass_g: "3.650,00",
    sex: "female",
    year: 2008
  },
  {
    id: 319,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50.9,
    bill_depth_mm: 19.1,
    flipper_length_mm: 196,
    body_mass_g: "3.550,00",
    sex: "male",
    year: 2008
  },
  {
    id: 320,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 45.5,
    bill_depth_mm: 17,
    flipper_length_mm: 196,
    body_mass_g: "3.500,00",
    sex: "female",
    year: 2008
  },
  {
    id: 321,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50.9,
    bill_depth_mm: 17.9,
    flipper_length_mm: 196,
    body_mass_g: "3.675,00",
    sex: "female",
    year: 2009
  },
  {
    id: 322,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50.8,
    bill_depth_mm: 18.5,
    flipper_length_mm: 201,
    body_mass_g: "4.450,00",
    sex: "male",
    year: 2009
  },
  {
    id: 323,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50.1,
    bill_depth_mm: 17.9,
    flipper_length_mm: 190,
    body_mass_g: "3.400,00",
    sex: "female",
    year: 2009
  },
  {
    id: 324,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 49,
    bill_depth_mm: 19.6,
    flipper_length_mm: 212,
    body_mass_g: "4.300,00",
    sex: "male",
    year: 2009
  },
  {
    id: 325,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 51.5,
    bill_depth_mm: 18.7,
    flipper_length_mm: 187,
    body_mass_g: "3.250,00",
    sex: "male",
    year: 2009
  },
  {
    id: 326,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 49.8,
    bill_depth_mm: 17.3,
    flipper_length_mm: 198,
    body_mass_g: "3.675,00",
    sex: "female",
    year: 2009
  },
  {
    id: 327,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 48.1,
    bill_depth_mm: 16.4,
    flipper_length_mm: 199,
    body_mass_g: "3.325,00",
    sex: "female",
    year: 2009
  },
  {
    id: 328,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 51.4,
    bill_depth_mm: 19,
    flipper_length_mm: 201,
    body_mass_g: "3.950,00",
    sex: "male",
    year: 2009
  },
  {
    id: 329,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 45.7,
    bill_depth_mm: 17.3,
    flipper_length_mm: 193,
    body_mass_g: "3.600,00",
    sex: "female",
    year: 2009
  },
  {
    id: 330,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50.7,
    bill_depth_mm: 19.7,
    flipper_length_mm: 203,
    body_mass_g: "4.050,00",
    sex: "male",
    year: 2009
  },
  {
    id: 331,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 42.5,
    bill_depth_mm: 17.3,
    flipper_length_mm: 187,
    body_mass_g: "3.350,00",
    sex: "female",
    year: 2009
  },
  {
    id: 332,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 52.2,
    bill_depth_mm: 18.8,
    flipper_length_mm: 197,
    body_mass_g: "3.450,00",
    sex: "male",
    year: 2009
  },
  {
    id: 333,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 45.2,
    bill_depth_mm: 16.6,
    flipper_length_mm: 191,
    body_mass_g: "3.250,00",
    sex: "female",
    year: 2009
  },
  {
    id: 334,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 49.3,
    bill_depth_mm: 19.9,
    flipper_length_mm: 203,
    body_mass_g: "4.050,00",
    sex: "male",
    year: 2009
  },
  {
    id: 335,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50.2,
    bill_depth_mm: 18.8,
    flipper_length_mm: 202,
    body_mass_g: "3.800,00",
    sex: "male",
    year: 2009
  },
  {
    id: 336,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 45.6,
    bill_depth_mm: 19.4,
    flipper_length_mm: 194,
    body_mass_g: "3.525,00",
    sex: "female",
    year: 2009
  },
  {
    id: 337,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 51.9,
    bill_depth_mm: 19.5,
    flipper_length_mm: 206,
    body_mass_g: "3.950,00",
    sex: "male",
    year: 2009
  },
  {
    id: 338,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 46.8,
    bill_depth_mm: 16.5,
    flipper_length_mm: 189,
    body_mass_g: "3.650,00",
    sex: "female",
    year: 2009
  },
  {
    id: 339,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 45.7,
    bill_depth_mm: 17,
    flipper_length_mm: 195,
    body_mass_g: "3.650,00",
    sex: "female",
    year: 2009
  },
  {
    id: 340,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 55.8,
    bill_depth_mm: 19.8,
    flipper_length_mm: 207,
    body_mass_g: "4.000,00",
    sex: "male",
    year: 2009
  },
  {
    id: 341,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 43.5,
    bill_depth_mm: 18.1,
    flipper_length_mm: 202,
    body_mass_g: "3.400,00",
    sex: "female",
    year: 2009
  },
  {
    id: 342,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 49.6,
    bill_depth_mm: 18.2,
    flipper_length_mm: 193,
    body_mass_g: "3.775,00",
    sex: "male",
    year: 2009
  },
  {
    id: 343,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50.8,
    bill_depth_mm: 19,
    flipper_length_mm: 210,
    body_mass_g: "4.100,00",
    sex: "male",
    year: 2009
  },
  {
    id: 344,
   species: "Pulau Tidung",
   island: "Dream",
    bill_length_mm: 50.2,
    bill_depth_mm: 18.7,
    flipper_length_mm: 198,
    body_mass_g: "3.775,00",
    sex: "female",
    year: 2009
  }
];

app.get('/',(req,res) => {
    res.send('Welcome to API Toor Apps');
});

app.get('/api/findUs/',(req,res) => {
    res.send('This page is empty. Perhaps you could add into this');
});

app.get('/api/listChoices', (req, res) => {
    res.send(listChoices);
});

app.patch('/api/listChoices/:id',(req,res) => {
   const { id } = req.params;
   const { species } = req.body;

   const updateSpecies = listChoices.find((Choice) => Choice.id === id);

   if(species) Choice.species = species;

   send.res(`User ${id} updated`);

  });

app.delete('/api/listChoices/:id',(req,res) => {
  const Choice = listChoices.find(c => c.id === parseInt(req.params.id));
  if (!Choice) res.status(400).send('Given ID is not exist');

  const index = listChoices.indexOf(Choice);
  listChoices.splice(index, 1);

  res.send(Choice);
});

app.post('/api/listChoices/', (req,res) => {
  const Choice = req.body;

  listChoices.push(Choice);

  res.send(`User Added with name ${Choice.species} to database`);
});

app.get(`/api/listChoices/:id`, (req, res) => {
    const Choice = listChoices.find(c => c.id === parseInt(req.params.id));
    if (!Choice) res.status(404).send('Sorry No Year Registered');
    res.send(Choice)
});

app.listen(port, () => console.log(`listening on port ${port}`));

function validateChoice(Choice){
  const schema = {
    jenisLokasi: Joi.string().min(6).required()
  };

  return Joi.validate(Choice, schema);
}